### PR TITLE
Source and Comment Typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@berndhahnebach ping

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
@berndhahnebach ping

**Comment by luzpaz** [comment]
@berndhahnebach please acknowledge

**Comment by luzpaz** [comment]
@berndhahnebach ack please

**Comment by berndhahnebach** [comment]
sorry I some how missed this for month

**Comment by luzpaz** [comment]
lol, more like a year :) 
Thanks for merging

**Comment by berndhahnebach** [comment]
It's done when it's done ;-) but it did not merge somehow. Might be to old anyway ... I did it manually ... https://github.com/berndhahnebach/BOLTSFC/commit/d1c6fa2d99a2120ccbe756df712c4c1059b9c1b0

**Pull request merged**
